'use strict';

const FEATURES_LANGS = {
  en: {
    lang: 'en',
    htmlLang: 'en',
    title: 'Features — How Lalabuba Works | Free AI Coloring Pages for Kids',
    description: 'Discover Lalabuba\'s features: AI coloring page generation, color-by-number, 4 difficulty levels, daily challenge, multiplayer, and more. Free for all ages.',
    h1: 'How Lalabuba Works',
    heroDesc: 'Type any subject, watch AI draw it, color it in. It\'s that simple — and completely free.',
    heroCta: 'Try it now — it\'s free →',
    stepsHeading: '4 Steps to Your Perfect Coloring Page',
    stepsSub: 'No account needed. No download required. Works in any browser.',
    steps: [
      { num: '1', title: 'Type any subject', desc: 'Type anything you want to draw — a dragon, butterfly, castle, unicorn, or your own creative idea. Our AI understands thousands of subjects.' },
      { num: '2', title: 'Click Draw!', desc: 'Our AI generates a custom line-art coloring page for your subject in seconds — every image is unique and tailored to your request.' },
      { num: '3', title: 'Color it in', desc: 'Tap a color from the palette, then tap any numbered region to fill it. Or switch to the pencil tool for freehand drawing. Undo anytime.' },
      { num: '4', title: 'Save, print, or challenge a friend', desc: 'Download your finished masterpiece, print it out, or use the Challenge button to share the same picture with a friend and race to finish first!' },
    ],
    featuresHeading: 'Everything You Need to Create & Color',
    featuresSub: 'Built for kids, loved by the whole family.',
    features: [
      { icon: '🤖', title: 'AI Image Generation', desc: 'Powered by state-of-the-art FLUX AI. Every coloring page is drawn from scratch — no two pictures are exactly the same.' },
      { icon: '🔢', title: 'Color by Number', desc: 'Every region is numbered and matched to a palette. Perfect for young children learning colors and numbers.' },
      { icon: '⭐', title: '4 Difficulty Levels', desc: 'Easy (3–6 regions) to Extreme (mandala-style complexity). Find the perfect challenge for any age.' },
      { icon: '🖌️', title: '3 Color Palettes', desc: 'Classic Crayons (24 vibrant colors), Soft Pastels, or Nature tones. Plus a Max mode with 256 colors.' },
      { icon: '✏️', title: 'Freehand Drawing', desc: 'Switch to the pencil tool to add your own details on top of the coloring page. Full undo history included.' },
      { icon: '🖨️', title: 'Print & Save', desc: 'Download your coloring page as a PNG or send it straight to the printer. Great for offline coloring books.' },
      { icon: '🏆', title: 'Multiplayer Challenge', desc: 'Share a link so a friend colors the same picture at the same time. A timer shows who finishes first!' },
      { icon: '🌟', title: 'Daily Challenge', desc: 'Every day a new word appears for everyone. Draw the daily word and compare results with friends.' },
      { icon: '🖼️', title: 'Personal Gallery', desc: 'Completed pictures are automatically saved to your device gallery. Revisit and continue them anytime.' },
      { icon: '🌍', title: '12 Languages', desc: 'Available in English, German, French, Spanish, Russian, Italian, Portuguese, Dutch, Polish, Turkish, Chinese, and Hindi.' },
      { icon: '📱', title: 'iOS & Android Apps', desc: 'Use Lalabuba in any browser or download the native app for iOS and Android for the best mobile experience.' },
      { icon: '🆓', title: '100% Free', desc: 'No account, no subscription, no ads, no in-app purchases. Lalabuba is free today and always will be.' },
    ],
    badgesHeading: 'Available Everywhere',
    badgesSub: 'Works in any browser. Also available as a native app.',
    faqHeading: 'Frequently Asked Questions',
    faqItems: [
      { q: 'Is Lalabuba really free?', a: 'Yes, completely free. There are no ads, no subscriptions, no in-app purchases, and no account required. Lalabuba is free for everyone.' },
      { q: 'What ages is it designed for?', a: 'Lalabuba is designed for children ages 3–12, but enjoyed by the whole family. Easy mode (6 regions, 6 colors) is perfect for toddlers; Extreme mode creates mandala-level complexity for older kids and adults.' },
      { q: 'Can I print the coloring pages?', a: 'Yes! Click the Print button to print the blank line art for traditional paper coloring, or print your finished colored digital version to keep or frame.' },
      { q: 'Does it work on tablets and phones?', a: 'Yes. Lalabuba is fully responsive and works in any modern browser. For the best experience on mobile, download the native iOS or Android app with touch-optimized controls and pinch-to-zoom.' },
      { q: 'How does the multiplayer challenge work?', a: 'After generating a coloring page, click "Challenge a friend" to get a shareable link. Anyone who opens the link sees the exact same picture. A timer runs for both players — whoever finishes coloring first wins!' },
    ],
    ctaHeading: 'Ready to Start Coloring?',
    ctaSub: 'No sign-up needed. Your first coloring page is one click away.',
    ctaBtn: 'Open Lalabuba — it\'s free →',
    ctaOr: 'or explore',
    ctaColoringPages: 'popular coloring page topics',
  },

  de: {
    lang: 'de',
    htmlLang: 'de',
    title: 'Funktionen — Wie Lalabuba funktioniert | Kostenlose KI-Ausmalbilder für Kinder',
    description: 'Entdecke die Funktionen von Lalabuba: KI-Ausmalbilder, Malen nach Zahlen, 4 Schwierigkeitsstufen, tägliche Challenge, Mehrspieler und mehr. Kostenlos für alle.',
    h1: 'Wie Lalabuba funktioniert',
    heroDesc: 'Gib ein Thema ein, schau zu wie die KI es zeichnet, und male es aus. So einfach ist das — und völlig kostenlos.',
    heroCta: 'Jetzt ausprobieren — kostenlos →',
    stepsHeading: '4 Schritte zu deinem perfekten Ausmalbild',
    stepsSub: 'Kein Konto nötig. Kein Download erforderlich. Funktioniert in jedem Browser.',
    steps: [
      { num: '1', title: 'Gib ein Thema ein', desc: 'Gib alles ein, was du zeichnen möchtest — einen Drachen, Schmetterling, ein Schloss, ein Einhorn oder deine eigene kreative Idee. Unsere KI versteht tausende von Themen.' },
      { num: '2', title: 'Klick auf Zeichnen!', desc: 'Unsere KI erstellt in Sekunden ein individuelles Ausmalbild für dein Thema — jedes Bild ist einzigartig und auf deine Anfrage zugeschnitten.' },
      { num: '3', title: 'Male es aus', desc: 'Tippe auf eine Farbe aus der Palette, dann auf einen nummerierten Bereich zum Ausfüllen. Oder wechsle zum Bleistiftwerkzeug für Freihandzeichnen. Rückgängig machen jederzeit möglich.' },
      { num: '4', title: 'Speichern, drucken oder Freunde herausfordern', desc: 'Lade dein fertiges Meisterwerk herunter, drucke es aus oder nutze den Herausforderungs-Button, um dasselbe Bild mit einem Freund zu teilen und um die Wette zu malen!' },
    ],
    featuresHeading: 'Alles, was du zum Erstellen und Ausmalen brauchst',
    featuresSub: 'Für Kinder gebaut, von der ganzen Familie geliebt.',
    features: [
      { icon: '🤖', title: 'KI-Bildgenerierung', desc: 'Angetrieben von modernster FLUX AI. Jedes Ausmalbild wird von Grund auf neu gezeichnet — keine zwei Bilder sind genau gleich.' },
      { icon: '🔢', title: 'Malen nach Zahlen', desc: 'Jeder Bereich ist nummeriert und einer Palette zugeordnet. Perfekt für kleine Kinder, die Farben und Zahlen lernen.' },
      { icon: '⭐', title: '4 Schwierigkeitsstufen', desc: 'Einfach (3–6 Bereiche) bis Extrem (Mandala-artige Komplexität). Finde die perfekte Herausforderung für jedes Alter.' },
      { icon: '🖌️', title: '3 Farbpaletten', desc: 'Klassische Buntstifte (24 leuchtende Farben), sanfte Pastelltöne oder Naturtöne. Dazu ein Max-Modus mit 256 Farben.' },
      { icon: '✏️', title: 'Freihandzeichnen', desc: 'Wechsle zum Bleistiftwerkzeug, um eigene Details auf das Ausmalbild zu zeichnen. Mit vollständiger Rückgängig-Funktion.' },
      { icon: '🖨️', title: 'Drucken & Speichern', desc: 'Lade dein Ausmalbild als PNG herunter oder schicke es direkt zum Drucker. Ideal für Offline-Malbücher.' },
      { icon: '🏆', title: 'Mehrspieler-Challenge', desc: 'Teile einen Link, damit ein Freund dasselbe Bild gleichzeitig ausmalt. Ein Timer zeigt, wer zuerst fertig ist!' },
      { icon: '🌟', title: 'Tägliche Challenge', desc: 'Jeden Tag erscheint ein neues Wort für alle. Zeichne das Tageswort und vergleiche Ergebnisse mit Freunden.' },
      { icon: '🖼️', title: 'Persönliche Galerie', desc: 'Fertige Bilder werden automatisch in deiner Gerätegalerie gespeichert. Jederzeit zurückblicken und weiter ausmalen.' },
      { icon: '🌍', title: '12 Sprachen', desc: 'Verfügbar auf Englisch, Deutsch, Französisch, Spanisch, Russisch, Italienisch, Portugiesisch, Niederländisch, Polnisch, Türkisch, Chinesisch und Hindi.' },
      { icon: '📱', title: 'iOS & Android Apps', desc: 'Nutze Lalabuba in jedem Browser oder lade die native App für iOS und Android herunter, um die beste mobile Erfahrung zu haben.' },
      { icon: '🆓', title: '100% Kostenlos', desc: 'Kein Konto, kein Abonnement, keine Werbung, keine In-App-Käufe. Lalabuba ist heute kostenlos und wird es immer bleiben.' },
    ],
    badgesHeading: 'Überall verfügbar',
    badgesSub: 'Funktioniert in jedem Browser. Auch als native App erhältlich.',
    faqHeading: 'Häufig gestellte Fragen',
    faqItems: [
      { q: 'Ist Lalabuba wirklich kostenlos?', a: 'Ja, völlig kostenlos. Es gibt keine Werbung, keine Abonnements, keine In-App-Käufe und kein Konto erforderlich. Lalabuba ist für alle kostenlos.' },
      { q: 'Für welches Alter ist es geeignet?', a: 'Lalabuba ist für Kinder im Alter von 3–12 Jahren konzipiert, macht aber der ganzen Familie Spaß. Der einfache Modus (6 Bereiche, 6 Farben) ist ideal für Kleinkinder; der extreme Modus bietet Mandala-ähnliche Komplexität für ältere Kinder und Erwachsene.' },
      { q: 'Kann ich die Ausmalbilder drucken?', a: 'Ja! Klicke auf den Drucken-Button, um die leere Linienzeichnung für traditionelles Papiermalen auszudrucken, oder drucke deine fertige digitale Version zum Behalten oder Einrahmen.' },
      { q: 'Funktioniert es auf Tablets und Smartphones?', a: 'Ja. Lalabuba ist vollständig responsiv und funktioniert in jedem modernen Browser. Für die beste Erfahrung auf Mobilgeräten lade die native iOS- oder Android-App mit touch-optimierten Bedienelementen und Pinch-to-Zoom herunter.' },
      { q: 'Wie funktioniert die Mehrspieler-Challenge?', a: 'Nach dem Erstellen eines Ausmalbilds klicke auf "Freund herausfordern", um einen teilbaren Link zu erhalten. Jeder, der den Link öffnet, sieht genau dasselbe Bild. Ein Timer läuft für beide Spieler — wer zuerst fertig ist, gewinnt!' },
    ],
    ctaHeading: 'Bereit mit dem Ausmalen zu beginnen?',
    ctaSub: 'Keine Anmeldung nötig. Dein erstes Ausmalbild ist nur einen Klick entfernt.',
    ctaBtn: 'Lalabuba öffnen — kostenlos →',
    ctaOr: 'oder entdecke',
    ctaColoringPages: 'beliebte Ausmalbilder-Themen',
  },

  fr: {
    lang: 'fr',
    htmlLang: 'fr',
    title: 'Fonctionnalités — Comment fonctionne Lalabuba | Coloriages IA gratuits pour enfants',
    description: 'Découvre les fonctionnalités de Lalabuba : génération de coloriages IA, coloriage par numéros, 4 niveaux de difficulté, défi quotidien, multijoueur et plus. Gratuit pour tous.',
    h1: 'Comment fonctionne Lalabuba',
    heroDesc: 'Tape un sujet, regarde l\'IA le dessiner, puis colorie-le. C\'est aussi simple que ça — et entièrement gratuit.',
    heroCta: 'Essaie maintenant — c\'est gratuit →',
    stepsHeading: '4 étapes pour ton coloriage parfait',
    stepsSub: 'Pas de compte nécessaire. Pas de téléchargement requis. Fonctionne dans n\'importe quel navigateur.',
    steps: [
      { num: '1', title: 'Tape un sujet', desc: 'Tape tout ce que tu veux dessiner — un dragon, un papillon, un château, une licorne ou ta propre idée créative. Notre IA comprend des milliers de sujets.' },
      { num: '2', title: 'Clique sur Dessiner !', desc: 'Notre IA génère en quelques secondes un coloriage personnalisé pour ton sujet — chaque image est unique et adaptée à ta demande.' },
      { num: '3', title: 'Colorie-le', desc: 'Appuie sur une couleur de la palette, puis appuie sur une zone numérotée pour la remplir. Ou passe à l\'outil crayon pour dessiner à main levée. Annulation possible à tout moment.' },
      { num: '4', title: 'Sauvegarde, imprime ou défie un ami', desc: 'Télécharge ton chef-d\'œuvre fini, imprime-le, ou utilise le bouton Défi pour partager la même image avec un ami et voir qui termine en premier !' },
    ],
    featuresHeading: 'Tout ce dont tu as besoin pour créer et colorier',
    featuresSub: 'Conçu pour les enfants, adoré par toute la famille.',
    features: [
      { icon: '🤖', title: 'Génération d\'images IA', desc: 'Propulsé par FLUX AI de pointe. Chaque coloriage est dessiné de zéro — deux images ne sont jamais exactement identiques.' },
      { icon: '🔢', title: 'Coloriage par numéros', desc: 'Chaque zone est numérotée et associée à une palette. Parfait pour les jeunes enfants qui apprennent les couleurs et les chiffres.' },
      { icon: '⭐', title: '4 niveaux de difficulté', desc: 'Facile (3–6 zones) à Extrême (complexité de style mandala). Trouve le défi parfait pour chaque âge.' },
      { icon: '🖌️', title: '3 palettes de couleurs', desc: 'Crayons classiques (24 couleurs vives), pastels doux ou tons nature. Plus un mode Max avec 256 couleurs.' },
      { icon: '✏️', title: 'Dessin à main levée', desc: 'Passe à l\'outil crayon pour ajouter tes propres détails sur le coloriage. Historique d\'annulation complet inclus.' },
      { icon: '🖨️', title: 'Imprimer et sauvegarder', desc: 'Télécharge ton coloriage en PNG ou envoie-le directement à l\'imprimante. Idéal pour les livres de coloriage hors ligne.' },
      { icon: '🏆', title: 'Défi multijoueur', desc: 'Partage un lien pour qu\'un ami colorie la même image en même temps. Un minuteur indique qui termine en premier !' },
      { icon: '🌟', title: 'Défi quotidien', desc: 'Chaque jour, un nouveau mot apparaît pour tout le monde. Dessine le mot du jour et compare les résultats avec des amis.' },
      { icon: '🖼️', title: 'Galerie personnelle', desc: 'Les images terminées sont automatiquement sauvegardées dans la galerie de ton appareil. Reviens les voir et continue-les à tout moment.' },
      { icon: '🌍', title: '12 langues', desc: 'Disponible en anglais, allemand, français, espagnol, russe, italien, portugais, néerlandais, polonais, turc, chinois et hindi.' },
      { icon: '📱', title: 'Applications iOS et Android', desc: 'Utilise Lalabuba dans n\'importe quel navigateur ou télécharge l\'application native pour iOS et Android pour la meilleure expérience mobile.' },
      { icon: '🆓', title: '100% gratuit', desc: 'Pas de compte, pas d\'abonnement, pas de publicité, pas d\'achats intégrés. Lalabuba est gratuit aujourd\'hui et le restera toujours.' },
    ],
    badgesHeading: 'Disponible partout',
    badgesSub: 'Fonctionne dans n\'importe quel navigateur. Aussi disponible en application native.',
    faqHeading: 'Questions fréquemment posées',
    faqItems: [
      { q: 'Lalabuba est-il vraiment gratuit ?', a: 'Oui, entièrement gratuit. Il n\'y a pas de publicité, pas d\'abonnements, pas d\'achats intégrés et aucun compte requis. Lalabuba est gratuit pour tous.' },
      { q: 'Pour quel âge est-il conçu ?', a: 'Lalabuba est conçu pour les enfants de 3 à 12 ans, mais apprécié par toute la famille. Le mode Facile (6 zones, 6 couleurs) est parfait pour les tout-petits ; le mode Extrême crée une complexité de niveau mandala pour les enfants plus âgés et les adultes.' },
      { q: 'Puis-je imprimer les coloriages ?', a: 'Oui ! Clique sur le bouton Imprimer pour imprimer le dessin vierge pour un coloriage traditionnel sur papier, ou imprime ta version colorée finie à conserver ou encadrer.' },
      { q: 'Fonctionne-t-il sur tablettes et téléphones ?', a: 'Oui. Lalabuba est entièrement responsive et fonctionne dans n\'importe quel navigateur moderne. Pour la meilleure expérience sur mobile, télécharge l\'application native iOS ou Android avec des commandes optimisées pour le tactile et le zoom par pincement.' },
      { q: 'Comment fonctionne le défi multijoueur ?', a: 'Après avoir généré un coloriage, clique sur « Défier un ami » pour obtenir un lien partageable. Quiconque ouvre le lien voit exactement la même image. Un minuteur tourne pour les deux joueurs — celui qui termine en premier a gagné !' },
    ],
    ctaHeading: 'Prêt(e) à commencer à colorier ?',
    ctaSub: 'Pas d\'inscription nécessaire. Ton premier coloriage est à portée d\'un clic.',
    ctaBtn: 'Ouvrir Lalabuba — c\'est gratuit →',
    ctaOr: 'ou explore',
    ctaColoringPages: 'les sujets de coloriage populaires',
  },

  es: {
    lang: 'es',
    htmlLang: 'es',
    title: 'Características — Cómo funciona Lalabuba | Páginas para colorear con IA gratuitas para niños',
    description: 'Descubre las características de Lalabuba: generación de páginas para colorear con IA, colorear por números, 4 niveles de dificultad, desafío diario, multijugador y más. Gratis para todos.',
    h1: 'Cómo funciona Lalabuba',
    heroDesc: 'Escribe cualquier tema, observa cómo la IA lo dibuja y coloréalo. Así de sencillo — y completamente gratis.',
    heroCta: 'Pruébalo ahora — es gratis →',
    stepsHeading: '4 pasos para tu página para colorear perfecta',
    stepsSub: 'Sin cuenta necesaria. Sin descarga requerida. Funciona en cualquier navegador.',
    steps: [
      { num: '1', title: 'Escribe cualquier tema', desc: 'Escribe lo que quieras dibujar — un dragón, una mariposa, un castillo, un unicornio o tu propia idea creativa. Nuestra IA entiende miles de temas.' },
      { num: '2', title: '¡Haz clic en Dibujar!', desc: 'Nuestra IA genera en segundos una página para colorear personalizada para tu tema — cada imagen es única y adaptada a tu solicitud.' },
      { num: '3', title: 'Coloréalo', desc: 'Toca un color de la paleta, luego toca cualquier región numerada para rellenarla. O cambia a la herramienta de lápiz para dibujar a mano libre. Deshacer en cualquier momento.' },
      { num: '4', title: 'Guarda, imprime o reta a un amigo', desc: 'Descarga tu obra maestra terminada, imprímela o usa el botón Desafío para compartir la misma imagen con un amigo y ver quién termina primero.' },
    ],
    featuresHeading: 'Todo lo que necesitas para crear y colorear',
    featuresSub: 'Creado para niños, amado por toda la familia.',
    features: [
      { icon: '🤖', title: 'Generación de imágenes con IA', desc: 'Potenciado por FLUX AI de última generación. Cada página para colorear se dibuja desde cero — ninguna imagen es exactamente igual.' },
      { icon: '🔢', title: 'Colorear por números', desc: 'Cada región está numerada y asignada a una paleta. Perfecto para niños pequeños que aprenden colores y números.' },
      { icon: '⭐', title: '4 niveles de dificultad', desc: 'Fácil (3–6 regiones) a Extremo (complejidad estilo mandala). Encuentra el desafío perfecto para cada edad.' },
      { icon: '🖌️', title: '3 paletas de colores', desc: 'Crayones clásicos (24 colores vibrantes), pasteles suaves o tonos naturales. Además de un modo Max con 256 colores.' },
      { icon: '✏️', title: 'Dibujo a mano libre', desc: 'Cambia a la herramienta de lápiz para añadir tus propios detalles encima de la página para colorear. Historial de deshacer completo incluido.' },
      { icon: '🖨️', title: 'Imprimir y guardar', desc: 'Descarga tu página para colorear como PNG o envíala directamente a la impresora. Ideal para libros para colorear sin conexión.' },
      { icon: '🏆', title: 'Desafío multijugador', desc: 'Comparte un enlace para que un amigo coloree la misma imagen al mismo tiempo. ¡Un temporizador muestra quién termina primero!' },
      { icon: '🌟', title: 'Desafío diario', desc: 'Cada día aparece una nueva palabra para todos. Dibuja la palabra del día y compara resultados con amigos.' },
      { icon: '🖼️', title: 'Galería personal', desc: 'Las imágenes terminadas se guardan automáticamente en la galería de tu dispositivo. Vuelve a verlas y continúalas en cualquier momento.' },
      { icon: '🌍', title: '12 idiomas', desc: 'Disponible en inglés, alemán, francés, español, ruso, italiano, portugués, neerlandés, polaco, turco, chino e hindi.' },
      { icon: '📱', title: 'Apps para iOS y Android', desc: 'Usa Lalabuba en cualquier navegador o descarga la app nativa para iOS y Android para la mejor experiencia móvil.' },
      { icon: '🆓', title: '100% gratis', desc: 'Sin cuenta, sin suscripción, sin anuncios, sin compras dentro de la app. Lalabuba es gratuito hoy y siempre lo será.' },
    ],
    badgesHeading: 'Disponible en todas partes',
    badgesSub: 'Funciona en cualquier navegador. También disponible como app nativa.',
    faqHeading: 'Preguntas frecuentes',
    faqItems: [
      { q: '¿Es Lalabuba realmente gratis?', a: 'Sí, completamente gratis. No hay anuncios, suscripciones, compras dentro de la app ni cuenta requerida. Lalabuba es gratuito para todos.' },
      { q: '¿Para qué edades está diseñado?', a: 'Lalabuba está diseñado para niños de 3 a 12 años, pero lo disfruta toda la familia. El modo Fácil (6 regiones, 6 colores) es perfecto para niños pequeños; el modo Extremo crea una complejidad de nivel mandala para niños mayores y adultos.' },
      { q: '¿Puedo imprimir las páginas para colorear?', a: '¡Sí! Haz clic en el botón Imprimir para imprimir el dibujo en blanco para colorear en papel de forma tradicional, o imprime tu versión digital coloreada terminada para guardarla o enmarcarla.' },
      { q: '¿Funciona en tablets y teléfonos?', a: 'Sí. Lalabuba es totalmente adaptable y funciona en cualquier navegador moderno. Para la mejor experiencia en móviles, descarga la app nativa iOS o Android con controles optimizados para táctil y zoom de pellizco.' },
      { q: '¿Cómo funciona el desafío multijugador?', a: 'Después de generar una página para colorear, haz clic en "Retar a un amigo" para obtener un enlace compartible. Cualquiera que abra el enlace ve exactamente la misma imagen. Un temporizador corre para ambos jugadores — ¡quien termine de colorear primero gana!' },
    ],
    ctaHeading: '¿Listo para empezar a colorear?',
    ctaSub: 'Sin registro necesario. Tu primera página para colorear está a un clic de distancia.',
    ctaBtn: 'Abrir Lalabuba — es gratis →',
    ctaOr: 'o explora',
    ctaColoringPages: 'temas populares para colorear',
  },

  pt: {
    lang: 'pt',
    htmlLang: 'pt',
    title: 'Funcionalidades — Como o Lalabuba funciona | Páginas de colorir com IA gratuitas para crianças',
    description: 'Descobre as funcionalidades do Lalabuba: geração de páginas de colorir com IA, colorir por números, 4 níveis de dificuldade, desafio diário, multijogador e mais. Grátis para todos.',
    h1: 'Como o Lalabuba funciona',
    heroDesc: 'Escreve qualquer tema, vê a IA desenhá-lo e pinta-o. É tão simples assim — e completamente grátis.',
    heroCta: 'Experimenta agora — é grátis →',
    stepsHeading: '4 passos para a tua página de colorir perfeita',
    stepsSub: 'Sem conta necessária. Sem download necessário. Funciona em qualquer navegador.',
    steps: [
      { num: '1', title: 'Escreve qualquer tema', desc: 'Escreve tudo o que quiseres desenhar — um dragão, uma borboleta, um castelo, um unicórnio ou a tua própria ideia criativa. A nossa IA compreende milhares de temas.' },
      { num: '2', title: 'Clica em Desenhar!', desc: 'A nossa IA gera em segundos uma página de colorir personalizada para o teu tema — cada imagem é única e adaptada ao teu pedido.' },
      { num: '3', title: 'Pinta-o', desc: 'Toca numa cor da paleta, depois toca em qualquer região numerada para a preencher. Ou muda para a ferramenta de lápis para desenho à mão livre. Desfazer em qualquer altura.' },
      { num: '4', title: 'Guarda, imprime ou desafia um amigo', desc: 'Faz download da tua obra-prima terminada, imprime-a ou usa o botão Desafio para partilhar a mesma imagem com um amigo e ver quem termina primeiro!' },
    ],
    featuresHeading: 'Tudo o que precisas para criar e colorir',
    featuresSub: 'Criado para crianças, adorado por toda a família.',
    features: [
      { icon: '🤖', title: 'Geração de imagens com IA', desc: 'Alimentado pelo FLUX AI de última geração. Cada página de colorir é desenhada do zero — nenhuma imagem é exatamente igual.' },
      { icon: '🔢', title: 'Colorir por números', desc: 'Cada região está numerada e associada a uma paleta. Perfeito para crianças pequenas que aprendem cores e números.' },
      { icon: '⭐', title: '4 níveis de dificuldade', desc: 'Fácil (3–6 regiões) a Extremo (complexidade estilo mandala). Encontra o desafio perfeito para qualquer idade.' },
      { icon: '🖌️', title: '3 paletas de cores', desc: 'Lápis clássicos (24 cores vibrantes), pastéis suaves ou tons naturais. Mais um modo Max com 256 cores.' },
      { icon: '✏️', title: 'Desenho à mão livre', desc: 'Muda para a ferramenta de lápis para adicionar os teus próprios detalhes na página de colorir. Histórico completo de desfazer incluído.' },
      { icon: '🖨️', title: 'Imprimir e guardar', desc: 'Faz download da tua página de colorir como PNG ou envia-a diretamente para a impressora. Ótimo para livros de colorir offline.' },
      { icon: '🏆', title: 'Desafio multijogador', desc: 'Partilha um link para um amigo colorir a mesma imagem ao mesmo tempo. Um cronómetro mostra quem termina primeiro!' },
      { icon: '🌟', title: 'Desafio diário', desc: 'Todos os dias aparece uma nova palavra para todos. Desenha a palavra do dia e compara resultados com amigos.' },
      { icon: '🖼️', title: 'Galeria pessoal', desc: 'As imagens terminadas são automaticamente guardadas na galeria do teu dispositivo. Revisita-as e continua-as a qualquer momento.' },
      { icon: '🌍', title: '12 idiomas', desc: 'Disponível em inglês, alemão, francês, espanhol, russo, italiano, português, holandês, polaco, turco, chinês e hindi.' },
      { icon: '📱', title: 'Apps para iOS e Android', desc: 'Usa o Lalabuba em qualquer navegador ou faz download da app nativa para iOS e Android para a melhor experiência móvel.' },
      { icon: '🆓', title: '100% grátis', desc: 'Sem conta, sem subscrição, sem anúncios, sem compras na app. O Lalabuba é grátis hoje e será sempre.' },
    ],
    badgesHeading: 'Disponível em todo o lado',
    badgesSub: 'Funciona em qualquer navegador. Também disponível como app nativa.',
    faqHeading: 'Perguntas frequentes',
    faqItems: [
      { q: 'O Lalabuba é mesmo grátis?', a: 'Sim, completamente grátis. Não há anúncios, subscrições, compras na app nem conta necessária. O Lalabuba é gratuito para todos.' },
      { q: 'Para que idades foi concebido?', a: 'O Lalabuba foi concebido para crianças dos 3 aos 12 anos, mas é apreciado por toda a família. O modo Fácil (6 regiões, 6 cores) é perfeito para os mais pequenos; o modo Extremo cria complexidade de nível mandala para crianças mais velhas e adultos.' },
      { q: 'Posso imprimir as páginas de colorir?', a: 'Sim! Clica no botão Imprimir para imprimir o desenho em branco para colorir em papel de forma tradicional, ou imprime a tua versão digital colorida terminada para guardar ou emoldurar.' },
      { q: 'Funciona em tablets e telemóveis?', a: 'Sim. O Lalabuba é totalmente responsivo e funciona em qualquer navegador moderno. Para a melhor experiência em dispositivos móveis, faz download da app nativa iOS ou Android com controlos otimizados para toque e zoom de beliscão.' },
      { q: 'Como funciona o desafio multijogador?', a: 'Depois de gerar uma página de colorir, clica em "Desafiar um amigo" para obter um link partilhável. Quem abrir o link vê exatamente a mesma imagem. Um cronómetro corre para ambos os jogadores — quem terminar de colorir primeiro ganha!' },
    ],
    ctaHeading: 'Pronto(a) para começar a colorir?',
    ctaSub: 'Sem registo necessário. A tua primeira página de colorir está a um clique de distância.',
    ctaBtn: 'Abrir Lalabuba — é grátis →',
    ctaOr: 'ou explora',
    ctaColoringPages: 'temas populares de colorir',
  },

  ru: {
    lang: 'ru',
    htmlLang: 'ru',
    title: 'Возможности — Как работает Lalabuba | Бесплатные раскраски с ИИ для детей',
    description: 'Узнай о возможностях Lalabuba: генерация раскрасок с ИИ, раскраска по номерам, 4 уровня сложности, ежедневный вызов, мультиплеер и многое другое. Бесплатно для всех.',
    h1: 'Как работает Lalabuba',
    heroDesc: 'Введи любую тему, наблюдай как ИИ её рисует, и раскрась. Всё так просто — и совершенно бесплатно.',
    heroCta: 'Попробуй сейчас — это бесплатно →',
    stepsHeading: '4 шага к твоей идеальной раскраске',
    stepsSub: 'Аккаунт не нужен. Загрузка не требуется. Работает в любом браузере.',
    steps: [
      { num: '1', title: 'Введи любую тему', desc: 'Введи всё, что хочешь нарисовать — дракона, бабочку, замок, единорога или свою собственную творческую идею. Наш ИИ понимает тысячи тем.' },
      { num: '2', title: 'Нажми Нарисовать!', desc: 'Наш ИИ создаёт индивидуальную раскраску для твоей темы за секунды — каждое изображение уникально и адаптировано под твой запрос.' },
      { num: '3', title: 'Раскрась', desc: 'Нажми на цвет из палитры, затем на любую пронумерованную область для заполнения. Или переключись на инструмент карандаша для свободного рисования. Отменить можно в любой момент.' },
      { num: '4', title: 'Сохрани, распечатай или вызови друга', desc: 'Скачай своё готовое произведение, распечатай его или используй кнопку «Вызов», чтобы поделиться тем же изображением с другом и поспорить, кто закончит первым!' },
    ],
    featuresHeading: 'Всё необходимое для создания и раскрашивания',
    featuresSub: 'Создано для детей, любимо всей семьёй.',
    features: [
      { icon: '🤖', title: 'Генерация изображений с ИИ', desc: 'Работает на основе передового FLUX AI. Каждая раскраска рисуется с нуля — никакие два изображения не совпадают.' },
      { icon: '🔢', title: 'Раскраска по номерам', desc: 'Каждая область пронумерована и сопоставлена с палитрой. Идеально для маленьких детей, изучающих цвета и числа.' },
      { icon: '⭐', title: '4 уровня сложности', desc: 'От Лёгкого (3–6 областей) до Экстремального (сложность в стиле мандалы). Найди идеальное испытание для любого возраста.' },
      { icon: '🖌️', title: '3 цветовые палитры', desc: 'Классические карандаши (24 яркие цвета), мягкие пастельные тона или природные оттенки. Плюс режим Max с 256 цветами.' },
      { icon: '✏️', title: 'Свободное рисование', desc: 'Переключись на инструмент карандаша, чтобы добавить собственные детали поверх раскраски. Полная история отмены включена.' },
      { icon: '🖨️', title: 'Печать и сохранение', desc: 'Скачай раскраску в формате PNG или отправь её прямо на принтер. Отлично подходит для офлайн-книжек-раскрасок.' },
      { icon: '🏆', title: 'Многопользовательское испытание', desc: 'Поделись ссылкой, чтобы друг раскрашивал то же изображение одновременно. Таймер покажет, кто закончит первым!' },
      { icon: '🌟', title: 'Ежедневный вызов', desc: 'Каждый день для всех появляется новое слово. Нарисуй слово дня и сравни результаты с друзьями.' },
      { icon: '🖼️', title: 'Личная галерея', desc: 'Завершённые изображения автоматически сохраняются в галерее твоего устройства. Возвращайся к ним и продолжай в любое время.' },
      { icon: '🌍', title: '12 языков', desc: 'Доступно на английском, немецком, французском, испанском, русском, итальянском, португальском, нидерландском, польском, турецком, китайском и хинди.' },
      { icon: '📱', title: 'Приложения для iOS и Android', desc: 'Используй Lalabuba в любом браузере или скачай нативное приложение для iOS и Android для лучшего мобильного опыта.' },
      { icon: '🆓', title: '100% бесплатно', desc: 'Без аккаунта, без подписки, без рекламы, без покупок в приложении. Lalabuba бесплатен сегодня и всегда будет бесплатным.' },
    ],
    badgesHeading: 'Доступно везде',
    badgesSub: 'Работает в любом браузере. Также доступно как нативное приложение.',
    faqHeading: 'Часто задаваемые вопросы',
    faqItems: [
      { q: 'Lalabuba действительно бесплатен?', a: 'Да, совершенно бесплатно. Нет рекламы, подписок, покупок в приложении и аккаунт не нужен. Lalabuba бесплатен для всех.' },
      { q: 'Для какого возраста он предназначен?', a: 'Lalabuba разработан для детей от 3 до 12 лет, но им наслаждается вся семья. Лёгкий режим (6 областей, 6 цветов) идеален для малышей; Экстремальный режим создаёт сложность уровня мандалы для старших детей и взрослых.' },
      { q: 'Можно ли распечатать раскраски?', a: 'Да! Нажми кнопку «Печать», чтобы распечатать пустой контур для традиционного раскрашивания на бумаге, или распечатай свою готовую цифровую версию, чтобы сохранить или оформить в рамку.' },
      { q: 'Работает ли это на планшетах и телефонах?', a: 'Да. Lalabuba полностью адаптивен и работает в любом современном браузере. Для лучшего опыта на мобильных устройствах скачай нативное приложение iOS или Android с оптимизированными сенсорными элементами управления и масштабированием щипком.' },
      { q: 'Как работает многопользовательское испытание?', a: 'После создания раскраски нажми «Вызвать друга», чтобы получить ссылку для обмена. Все, кто откроет ссылку, увидят то же самое изображение. Таймер идёт для обоих игроков — кто закончит раскрашивание первым, тот победит!' },
    ],
    ctaHeading: 'Готов(а) начать раскрашивать?',
    ctaSub: 'Регистрация не нужна. Твоя первая раскраска в одном клике.',
    ctaBtn: 'Открыть Lalabuba — бесплатно →',
    ctaOr: 'или изучи',
    ctaColoringPages: 'популярные темы раскрасок',
  },

  it: {
    lang: 'it',
    htmlLang: 'it',
    title: 'Funzionalità — Come funziona Lalabuba | Pagine da colorare con IA gratuite per bambini',
    description: 'Scopri le funzionalità di Lalabuba: generazione di pagine da colorare con IA, colorare per numeri, 4 livelli di difficoltà, sfida giornaliera, multigiocatore e altro. Gratuito per tutti.',
    h1: 'Come funziona Lalabuba',
    heroDesc: 'Digita un argomento, guarda l\'IA disegnarlo e coloralo. È così semplice — e completamente gratuito.',
    heroCta: 'Provalo adesso — è gratis →',
    stepsHeading: '4 passi per la tua pagina da colorare perfetta',
    stepsSub: 'Nessun account necessario. Nessun download richiesto. Funziona in qualsiasi browser.',
    steps: [
      { num: '1', title: 'Digita un argomento', desc: 'Digita qualsiasi cosa tu voglia disegnare — un drago, una farfalla, un castello, un unicorno o la tua idea creativa. La nostra IA capisce migliaia di argomenti.' },
      { num: '2', title: 'Clicca su Disegna!', desc: 'La nostra IA genera in pochi secondi una pagina da colorare personalizzata per il tuo argomento — ogni immagine è unica e adattata alla tua richiesta.' },
      { num: '3', title: 'Colorala', desc: 'Tocca un colore dalla tavolozza, poi tocca qualsiasi regione numerata per riempirla. O passa allo strumento matita per il disegno a mano libera. Annulla in qualsiasi momento.' },
      { num: '4', title: 'Salva, stampa o sfida un amico', desc: 'Scarica il tuo capolavoro finito, stampalo o usa il pulsante Sfida per condividere la stessa immagine con un amico e gareggiare a chi finisce per primo!' },
    ],
    featuresHeading: 'Tutto il necessario per creare e colorare',
    featuresSub: 'Fatto per i bambini, amato da tutta la famiglia.',
    features: [
      { icon: '🤖', title: 'Generazione di immagini con IA', desc: 'Alimentato da FLUX AI all\'avanguardia. Ogni pagina da colorare viene disegnata da zero — nessuna immagine è esattamente uguale.' },
      { icon: '🔢', title: 'Colorare per numeri', desc: 'Ogni regione è numerata e abbinata a una tavolozza. Perfetto per i bambini piccoli che imparano i colori e i numeri.' },
      { icon: '⭐', title: '4 livelli di difficoltà', desc: 'Facile (3–6 regioni) fino a Estremo (complessità stile mandala). Trova la sfida perfetta per ogni età.' },
      { icon: '🖌️', title: '3 tavolozze di colori', desc: 'Pastelli classici (24 colori vivaci), pastelli morbidi o tonalità naturali. Più una modalità Max con 256 colori.' },
      { icon: '✏️', title: 'Disegno a mano libera', desc: 'Passa allo strumento matita per aggiungere i tuoi dettagli sulla pagina da colorare. Cronologia di annullamento completa inclusa.' },
      { icon: '🖨️', title: 'Stampa e salva', desc: 'Scarica la tua pagina da colorare come PNG o inviala direttamente alla stampante. Ottimo per libri da colorare offline.' },
      { icon: '🏆', title: 'Sfida multigiocatore', desc: 'Condividi un link per far colorare a un amico la stessa immagine contemporaneamente. Un timer mostra chi finisce per primo!' },
      { icon: '🌟', title: 'Sfida giornaliera', desc: 'Ogni giorno appare una nuova parola per tutti. Disegna la parola del giorno e confronta i risultati con gli amici.' },
      { icon: '🖼️', title: 'Galleria personale', desc: 'Le immagini completate vengono automaticamente salvate nella galleria del tuo dispositivo. Rivisitale e continuale in qualsiasi momento.' },
      { icon: '🌍', title: '12 lingue', desc: 'Disponibile in inglese, tedesco, francese, spagnolo, russo, italiano, portoghese, olandese, polacco, turco, cinese e hindi.' },
      { icon: '📱', title: 'App per iOS e Android', desc: 'Usa Lalabuba in qualsiasi browser o scarica l\'app nativa per iOS e Android per la migliore esperienza mobile.' },
      { icon: '🆓', title: '100% gratuito', desc: 'Nessun account, nessun abbonamento, nessuna pubblicità, nessun acquisto in-app. Lalabuba è gratuito oggi e lo sarà sempre.' },
    ],
    badgesHeading: 'Disponibile ovunque',
    badgesSub: 'Funziona in qualsiasi browser. Disponibile anche come app nativa.',
    faqHeading: 'Domande frequenti',
    faqItems: [
      { q: 'Lalabuba è davvero gratuito?', a: 'Sì, completamente gratuito. Non ci sono pubblicità, abbonamenti, acquisti in-app né account richiesto. Lalabuba è gratuito per tutti.' },
      { q: 'Per quali età è progettato?', a: 'Lalabuba è progettato per bambini dai 3 ai 12 anni, ma è apprezzato da tutta la famiglia. La modalità Facile (6 regioni, 6 colori) è perfetta per i bambini piccoli; la modalità Estrema crea una complessità di livello mandala per bambini più grandi e adulti.' },
      { q: 'Posso stampare le pagine da colorare?', a: 'Sì! Clicca sul pulsante Stampa per stampare il disegno bianco per colorare su carta in modo tradizionale, o stampa la tua versione digitale colorata finita da conservare o incorniciare.' },
      { q: 'Funziona su tablet e telefoni?', a: 'Sì. Lalabuba è completamente responsive e funziona in qualsiasi browser moderno. Per la migliore esperienza su mobile, scarica l\'app nativa iOS o Android con controlli ottimizzati per il tocco e il pizzicamento per lo zoom.' },
      { q: 'Come funziona la sfida multigiocatore?', a: 'Dopo aver generato una pagina da colorare, clicca su "Sfida un amico" per ottenere un link condivisibile. Chiunque apra il link vede esattamente la stessa immagine. Un timer scorre per entrambi i giocatori — chi finisce di colorare per primo vince!' },
    ],
    ctaHeading: 'Pronto/a a iniziare a colorare?',
    ctaSub: 'Nessuna registrazione necessaria. La tua prima pagina da colorare è a un clic di distanza.',
    ctaBtn: 'Apri Lalabuba — è gratis →',
    ctaOr: 'o esplora',
    ctaColoringPages: 'argomenti popolari per colorare',
  },

  nl: {
    lang: 'nl',
    htmlLang: 'nl',
    title: 'Functies — Hoe Lalabuba werkt | Gratis AI-kleurplaten voor kinderen',
    description: 'Ontdek de functies van Lalabuba: AI-kleurplaatgeneratie, kleuren op nummer, 4 moeilijkheidsgraden, dagelijkse uitdaging, multiplayer en meer. Gratis voor iedereen.',
    h1: 'Hoe Lalabuba werkt',
    heroDesc: 'Typ een onderwerp, kijk toe hoe AI het tekent en kleur het in. Zo eenvoudig is het — en volledig gratis.',
    heroCta: 'Probeer het nu — het is gratis →',
    stepsHeading: '4 stappen naar jouw perfecte kleurplaat',
    stepsSub: 'Geen account nodig. Geen download vereist. Werkt in elke browser.',
    steps: [
      { num: '1', title: 'Typ een onderwerp', desc: 'Typ alles wat je wilt tekenen — een draak, vlinder, kasteel, eenhoorn of je eigen creatieve idee. Onze AI begrijpt duizenden onderwerpen.' },
      { num: '2', title: 'Klik op Tekenen!', desc: 'Onze AI genereert in seconden een aangepaste kleurplaat voor jouw onderwerp — elke afbeelding is uniek en afgestemd op jouw verzoek.' },
      { num: '3', title: 'Kleur het in', desc: 'Tik op een kleur uit het palet, dan op een genummerd gebied om het in te vullen. Of schakel over naar het potloodgereedschap voor vrij tekenen. Op elk moment ongedaan maken.' },
      { num: '4', title: 'Sla op, print of daag een vriend uit', desc: 'Download je voltooide meesterwerk, print het of gebruik de Uitdaging-knop om dezelfde afbeelding met een vriend te delen en te racen wie als eerste klaar is!' },
    ],
    featuresHeading: 'Alles wat je nodig hebt om te maken en kleuren',
    featuresSub: 'Gemaakt voor kinderen, geliefd door het hele gezin.',
    features: [
      { icon: '🤖', title: 'AI-beeldgeneratie', desc: 'Aangedreven door geavanceerde FLUX AI. Elke kleurplaat wordt van nul getekend — geen twee afbeeldingen zijn precies hetzelfde.' },
      { icon: '🔢', title: 'Kleuren op nummer', desc: 'Elk gebied is genummerd en gekoppeld aan een palet. Perfect voor jonge kinderen die kleuren en cijfers leren.' },
      { icon: '⭐', title: '4 moeilijkheidsgraden', desc: 'Makkelijk (3–6 gebieden) tot Extreem (mandala-achtige complexiteit). Vind de perfecte uitdaging voor elke leeftijd.' },
      { icon: '🖌️', title: '3 kleurenpaletten', desc: 'Klassieke krijtjes (24 levendige kleuren), zachte pastels of natuurtinten. Plus een Max-modus met 256 kleuren.' },
      { icon: '✏️', title: 'Vrij tekenen', desc: 'Schakel over naar het potloodgereedschap om je eigen details toe te voegen aan de kleurplaat. Volledige annuleringsgeschiedenis inbegrepen.' },
      { icon: '🖨️', title: 'Afdrukken en opslaan', desc: 'Download je kleurplaat als PNG of stuur hem direct naar de printer. Geweldig voor offline kleurboeken.' },
      { icon: '🏆', title: 'Multiplayer-uitdaging', desc: 'Deel een link zodat een vriend tegelijkertijd dezelfde afbeelding inkleurt. Een timer laat zien wie als eerste klaar is!' },
      { icon: '🌟', title: 'Dagelijkse uitdaging', desc: 'Elke dag verschijnt er een nieuw woord voor iedereen. Teken het dagelijkse woord en vergelijk resultaten met vrienden.' },
      { icon: '🖼️', title: 'Persoonlijke galerij', desc: 'Voltooide afbeeldingen worden automatisch opgeslagen in de galerij van je apparaat. Bekijk en hervat ze op elk moment.' },
      { icon: '🌍', title: '12 talen', desc: 'Beschikbaar in het Engels, Duits, Frans, Spaans, Russisch, Italiaans, Portugees, Nederlands, Pools, Turks, Chinees en Hindi.' },
      { icon: '📱', title: 'iOS- en Android-apps', desc: 'Gebruik Lalabuba in elke browser of download de native app voor iOS en Android voor de beste mobiele ervaring.' },
      { icon: '🆓', title: '100% gratis', desc: 'Geen account, geen abonnement, geen advertenties, geen in-app-aankopen. Lalabuba is vandaag gratis en zal dat altijd blijven.' },
    ],
    badgesHeading: 'Overal beschikbaar',
    badgesSub: 'Werkt in elke browser. Ook beschikbaar als native app.',
    faqHeading: 'Veelgestelde vragen',
    faqItems: [
      { q: 'Is Lalabuba echt gratis?', a: 'Ja, volledig gratis. Er zijn geen advertenties, abonnementen, in-app-aankopen en geen account vereist. Lalabuba is gratis voor iedereen.' },
      { q: 'Voor welke leeftijden is het ontworpen?', a: 'Lalabuba is ontworpen voor kinderen van 3 tot 12 jaar, maar wordt door het hele gezin genoten. De makkelijke modus (6 gebieden, 6 kleuren) is perfect voor peuters; de extreme modus creëert mandala-niveau complexiteit voor oudere kinderen en volwassenen.' },
      { q: 'Kan ik de kleurplaten afdrukken?', a: 'Ja! Klik op de Afdrukken-knop om het blanco lijnkunst af te drukken voor traditioneel papier kleuren, of druk je voltooide gekleurde digitale versie af om te bewaren of in te lijsten.' },
      { q: 'Werkt het op tablets en telefoons?', a: 'Ja. Lalabuba is volledig responsief en werkt in elke moderne browser. Voor de beste ervaring op mobiel, download de native iOS of Android app met touch-geoptimaliseerde bediening en knijp-om-in-te-zoomen.' },
      { q: 'Hoe werkt de multiplayer-uitdaging?', a: 'Na het genereren van een kleurplaat, klik op "Daag een vriend uit" om een deelbare link te krijgen. Iedereen die de link opent ziet precies dezelfde afbeelding. Een timer loopt voor beide spelers — wie als eerste klaar is met kleuren wint!' },
    ],
    ctaHeading: 'Klaar om te beginnen met kleuren?',
    ctaSub: 'Geen registratie nodig. Je eerste kleurplaat is één klik verwijderd.',
    ctaBtn: 'Open Lalabuba — het is gratis →',
    ctaOr: 'of verken',
    ctaColoringPages: 'populaire kleurplaatonderwerpen',
  },

  pl: {
    lang: 'pl',
    htmlLang: 'pl',
    title: 'Funkcje — Jak działa Lalabuba | Darmowe kolorowanki AI dla dzieci',
    description: 'Odkryj funkcje Lalabuba: generowanie kolorowanek AI, kolorowanie po numerach, 4 poziomy trudności, codzienne wyzwanie, tryb wieloosobowy i więcej. Bezpłatnie dla wszystkich.',
    h1: 'Jak działa Lalabuba',
    heroDesc: 'Wpisz dowolny temat, obserwuj jak AI go rysuje i pokoloruj go. To takie proste — i całkowicie bezpłatne.',
    heroCta: 'Wypróbuj teraz — to bezpłatne →',
    stepsHeading: '4 kroki do idealnej kolorowanki',
    stepsSub: 'Konto nie jest potrzebne. Pobieranie nie jest wymagane. Działa w każdej przeglądarce.',
    steps: [
      { num: '1', title: 'Wpisz dowolny temat', desc: 'Wpisz wszystko, co chcesz narysować — smoka, motyla, zamek, jednorożca lub własny pomysł. Nasza AI rozumie tysiące tematów.' },
      { num: '2', title: 'Kliknij Rysuj!', desc: 'Nasza AI generuje w kilka sekund spersonalizowaną kolorowankę dla twojego tematu — każdy obraz jest unikalny i dopasowany do twojego życzenia.' },
      { num: '3', title: 'Pokoloruj ją', desc: 'Dotknij koloru z palety, następnie dotknij dowolnego ponumerowanego obszaru, aby go wypełnić. Lub przełącz się na narzędzie ołówka dla rysowania odręcznego. Cofnij w dowolnym momencie.' },
      { num: '4', title: 'Zapisz, wydrukuj lub wyzwij przyjaciela', desc: 'Pobierz swoje gotowe arcydzieło, wydrukuj je lub użyj przycisku Wyzwanie, aby udostępnić ten sam rysunek przyjacielowi i sprawdzić, kto skończy pierwszy!' },
    ],
    featuresHeading: 'Wszystko czego potrzebujesz, żeby tworzyć i kolorować',
    featuresSub: 'Stworzone dla dzieci, uwielbiane przez całą rodzinę.',
    features: [
      { icon: '🤖', title: 'Generowanie obrazów AI', desc: 'Napędzany przez najnowocześniejszy FLUX AI. Każda kolorowanka jest rysowana od zera — żadne dwa obrazy nie są dokładnie takie same.' },
      { icon: '🔢', title: 'Kolorowanie po numerach', desc: 'Każdy obszar jest ponumerowany i dopasowany do palety. Idealne dla małych dzieci uczących się kolorów i cyfr.' },
      { icon: '⭐', title: '4 poziomy trudności', desc: 'Od Łatwego (3–6 obszarów) do Ekstremalnego (złożoność w stylu mandali). Znajdź idealne wyzwanie dla każdego wieku.' },
      { icon: '🖌️', title: '3 palety kolorów', desc: 'Klasyczne kredki (24 żywe kolory), delikatne pastele lub odcienie natury. Oraz tryb Max z 256 kolorami.' },
      { icon: '✏️', title: 'Rysowanie odręczne', desc: 'Przełącz się na narzędzie ołówka, aby dodać własne detale na kolorowance. Pełna historia cofania dołączona.' },
      { icon: '🖨️', title: 'Drukuj i zapisz', desc: 'Pobierz kolorowankę jako PNG lub wyślij ją bezpośrednio do drukarki. Świetne do kolorowanek offline.' },
      { icon: '🏆', title: 'Wyzwanie wieloosobowe', desc: 'Udostępnij link, aby przyjaciel kolorował ten sam rysunek jednocześnie. Licznik czasu pokazuje, kto kończy pierwszy!' },
      { icon: '🌟', title: 'Codzienne wyzwanie', desc: 'Każdego dnia pojawia się nowe słowo dla wszystkich. Narysuj dzisiejsze słowo i porównaj wyniki z przyjaciółmi.' },
      { icon: '🖼️', title: 'Osobista galeria', desc: 'Ukończone obrazy są automatycznie zapisywane w galerii urządzenia. Wróć do nich i kontynuuj w dowolnym momencie.' },
      { icon: '🌍', title: '12 języków', desc: 'Dostępne po angielsku, niemiecku, francusku, hiszpańsku, rosyjsku, włosku, portugalsku, niderlandzku, polsku, turecku, chińsku i hindi.' },
      { icon: '📱', title: 'Aplikacje na iOS i Android', desc: 'Używaj Lalabuba w dowolnej przeglądarce lub pobierz natywną aplikację na iOS i Android, aby uzyskać najlepsze wrażenia mobilne.' },
      { icon: '🆓', title: '100% bezpłatne', desc: 'Bez konta, bez subskrypcji, bez reklam, bez zakupów w aplikacji. Lalabuba jest bezpłatne dziś i zawsze będzie.' },
    ],
    badgesHeading: 'Dostępne wszędzie',
    badgesSub: 'Działa w każdej przeglądarce. Dostępne również jako natywna aplikacja.',
    faqHeading: 'Często zadawane pytania',
    faqItems: [
      { q: 'Czy Lalabuba jest naprawdę bezpłatne?', a: 'Tak, całkowicie bezpłatne. Nie ma reklam, subskrypcji, zakupów w aplikacji ani wymaganego konta. Lalabuba jest bezpłatne dla wszystkich.' },
      { q: 'Na jakie wieki jest przeznaczone?', a: 'Lalabuba jest przeznaczone dla dzieci w wieku 3–12 lat, ale cieszy się całą rodziną. Tryb Łatwy (6 obszarów, 6 kolorów) jest idealny dla maluchów; tryb Ekstremalny tworzy złożoność na poziomie mandali dla starszych dzieci i dorosłych.' },
      { q: 'Czy mogę drukować kolorowanki?', a: 'Tak! Kliknij przycisk Drukuj, aby wydrukować pustą grafikę do tradycyjnego kolorowania na papierze, lub wydrukuj ukończoną kolorową wersję cyfrową, aby ją zachować lub oprawić.' },
      { q: 'Czy działa na tabletach i telefonach?', a: 'Tak. Lalabuba jest w pełni responsywne i działa w każdej nowoczesnej przeglądarce. Aby uzyskać najlepsze wrażenia mobilne, pobierz natywną aplikację iOS lub Android z zoptymalizowanymi elementami dotykowymi i szczypaniem do zoomowania.' },
      { q: 'Jak działa wyzwanie wieloosobowe?', a: 'Po wygenerowaniu kolorowanki kliknij "Wyzwij przyjaciela", aby uzyskać link do udostępnienia. Każdy, kto otworzy link, widzi dokładnie ten sam obraz. Licznik czasu działa dla obu graczy — kto pierwszy skończy kolorowanie, wygrywa!' },
    ],
    ctaHeading: 'Gotowy(-a) zacząć kolorować?',
    ctaSub: 'Rejestracja nie jest wymagana. Twoja pierwsza kolorowanka jest o jedno kliknięcie.',
    ctaBtn: 'Otwórz Lalabuba — to bezpłatne →',
    ctaOr: 'lub odkryj',
    ctaColoringPages: 'popularne tematy kolorowanek',
  },

  tr: {
    lang: 'tr',
    htmlLang: 'tr',
    title: 'Özellikler — Lalabuba Nasıl Çalışır | Çocuklar için Ücretsiz Yapay Zeka Boyama Sayfaları',
    description: 'Lalabuba\'nın özelliklerini keşfet: yapay zeka boyama sayfası oluşturma, sayıya göre boyama, 4 zorluk seviyesi, günlük meydan okuma, çok oyunculu ve daha fazlası. Herkes için ücretsiz.',
    h1: 'Lalabuba Nasıl Çalışır',
    heroDesc: 'Bir konu yaz, yapay zekanın onu çizmesini izle ve boya. Bu kadar basit — ve tamamen ücretsiz.',
    heroCta: 'Şimdi dene — ücretsiz →',
    stepsHeading: 'Mükemmel Boyama Sayfan İçin 4 Adım',
    stepsSub: 'Hesap gerekmez. İndirme gerekmez. Herhangi bir tarayıcıda çalışır.',
    steps: [
      { num: '1', title: 'Bir konu yaz', desc: 'Çizmek istediğin her şeyi yaz — bir ejderha, kelebek, kale, tek boynuzlu at veya kendi yaratıcı fikrin. Yapay zekamız binlerce konuyu anlıyor.' },
      { num: '2', title: 'Çiz\'e tıkla!', desc: 'Yapay zekamız saniyeler içinde konun için özel bir boyama sayfası oluşturur — her görsel benzersizdir ve talebine göre özelleştirilmiştir.' },
      { num: '3', title: 'Boya', desc: 'Paletten bir renk seç, ardından doldurmak için numaralı bir bölgeye dokun. Ya da serbest el çizimi için kalem aracına geç. İstediğin zaman geri al.' },
      { num: '4', title: 'Kaydet, yazdır veya bir arkadaşa meydan oku', desc: 'Bitirdiğin şaheserini indir, yazdır ya da Meydan Okuma düğmesini kullanarak aynı resmi bir arkadaşınla paylaş ve kimin önce bitireceğini yarış!' },
    ],
    featuresHeading: 'Oluşturmak ve Boyamak için İhtiyacın Olan Her Şey',
    featuresSub: 'Çocuklar için yapıldı, tüm aile tarafından sevildi.',
    features: [
      { icon: '🤖', title: 'Yapay Zeka Görsel Oluşturma', desc: 'Son teknoloji FLUX AI ile güçlendirilmiştir. Her boyama sayfası sıfırdan çizilir — hiçbir iki resim tam olarak aynı değildir.' },
      { icon: '🔢', title: 'Sayıya Göre Boyama', desc: 'Her bölge numaralandırılmış ve bir paletle eşleştirilmiştir. Renkleri ve sayıları öğrenen küçük çocuklar için mükemmel.' },
      { icon: '⭐', title: '4 Zorluk Seviyesi', desc: 'Kolay (3–6 bölge) ile Aşırı (mandala tarzı karmaşıklık) arasında. Her yaş için mükemmel meydan okumayı bul.' },
      { icon: '🖌️', title: '3 Renk Paleti', desc: 'Klasik Mum Boya (24 canlı renk), Yumuşak Pasteller veya Doğa tonları. Ayrıca 256 renkli Max modu.' },
      { icon: '✏️', title: 'Serbest El Çizimi', desc: 'Boyama sayfasının üzerine kendi detaylarını eklemek için kalem aracına geç. Tam geri alma geçmişi dahildir.' },
      { icon: '🖨️', title: 'Yazdır ve Kaydet', desc: 'Boyama sayfanı PNG olarak indir veya doğrudan yazıcıya gönder. Çevrimdışı boyama kitapları için harika.' },
      { icon: '🏆', title: 'Çok Oyunculu Meydan Okuma', desc: 'Bir arkadaşın aynı resmi aynı anda boyaması için bir bağlantı paylaş. Bir zamanlayıcı kimin önce bitirdiğini gösterir!' },
      { icon: '🌟', title: 'Günlük Meydan Okuma', desc: 'Her gün herkes için yeni bir kelime belirir. Günlük kelimeyi çiz ve arkadaşlarınla sonuçları karşılaştır.' },
      { icon: '🖼️', title: 'Kişisel Galeri', desc: 'Tamamlanan resimler otomatik olarak cihazının galerisine kaydedilir. İstediğin zaman geri dön ve devam et.' },
      { icon: '🌍', title: '12 Dil', desc: 'İngilizce, Almanca, Fransızca, İspanyolca, Rusça, İtalyanca, Portekizce, Hollandaca, Lehçe, Türkçe, Çince ve Hintçe olarak mevcuttur.' },
      { icon: '📱', title: 'iOS ve Android Uygulamaları', desc: 'Lalabuba\'yı herhangi bir tarayıcıda kullan veya en iyi mobil deneyim için iOS ve Android yerel uygulamasını indir.' },
      { icon: '🆓', title: '%100 Ücretsiz', desc: 'Hesap yok, abonelik yok, reklam yok, uygulama içi satın alma yok. Lalabuba bugün ücretsizdir ve her zaman öyle olacaktır.' },
    ],
    badgesHeading: 'Her Yerde Mevcut',
    badgesSub: 'Herhangi bir tarayıcıda çalışır. Aynı zamanda yerel uygulama olarak da mevcuttur.',
    faqHeading: 'Sık Sorulan Sorular',
    faqItems: [
      { q: 'Lalabuba gerçekten ücretsiz mi?', a: 'Evet, tamamen ücretsiz. Reklam yok, abonelik yok, uygulama içi satın alma yok ve hesap gerekmez. Lalabuba herkes için ücretsizdir.' },
      { q: 'Hangi yaşlar için tasarlandı?', a: 'Lalabuba 3-12 yaş arası çocuklar için tasarlanmıştır, ancak tüm aile tarafından sevilmektedir. Kolay mod (6 bölge, 6 renk) küçük çocuklar için mükemmeldir; Aşırı mod daha büyük çocuklar ve yetişkinler için mandala düzeyinde karmaşıklık yaratır.' },
      { q: 'Boyama sayfalarını yazdırabilir miyim?', a: 'Evet! Geleneksel kağıt boyama için boş çizgisel sanatı yazdırmak üzere Yazdır düğmesine tıkla, ya da saklamak veya çerçevelemek için bitirdiğin renkli dijital versiyonunu yazdır.' },
      { q: 'Tabletlerde ve telefonlarda çalışıyor mu?', a: 'Evet. Lalabuba tamamen duyarlıdır ve herhangi bir modern tarayıcıda çalışır. Mobilde en iyi deneyim için, dokunmatik optimizasyonlu kontroller ve sıkıştırarak yakınlaştırma özelliklerine sahip yerel iOS veya Android uygulamasını indir.' },
      { q: 'Çok oyunculu meydan okuma nasıl çalışır?', a: 'Bir boyama sayfası oluşturduktan sonra, paylaşılabilir bir bağlantı almak için "Bir arkadaşa meydan oku"ya tıkla. Bağlantıyı açan herkes aynı resmi görür. Her iki oyuncu için de bir zamanlayıcı çalışır — boyamayı ilk bitiren kazanır!' },
    ],
    ctaHeading: 'Boyamaya Başlamaya Hazır Mısın?',
    ctaSub: 'Kayıt gerekmez. İlk boyama sayfan bir tıklama uzaklıkta.',
    ctaBtn: 'Lalabuba\'yı Aç — ücretsiz →',
    ctaOr: 'veya keşfet',
    ctaColoringPages: 'popüler boyama sayfası konuları',
  },

  zh: {
    lang: 'zh',
    htmlLang: 'zh',
    title: '功能 — Lalabuba 如何运作 | 免费儿童AI涂色页',
    description: '探索 Lalabuba 的功能：AI 涂色页生成、按数字涂色、4 个难度级别、每日挑战、多人游戏等。所有年龄免费。',
    h1: 'Lalabuba 如何运作',
    heroDesc: '输入任何主题，观看 AI 绘制它，再涂上颜色。就这么简单——完全免费。',
    heroCta: '立即尝试——免费 →',
    stepsHeading: '4 步完成你的完美涂色页',
    stepsSub: '无需账号。无需下载。在任何浏览器中均可使用。',
    steps: [
      { num: '1', title: '输入任何主题', desc: '输入你想画的任何内容——龙、蝴蝶、城堡、独角兽或你自己的创意。我们的 AI 能理解数千个主题。' },
      { num: '2', title: '点击绘制！', desc: '我们的 AI 在几秒钟内为你的主题生成自定义涂色页——每张图片都是独特的，并根据你的请求量身定制。' },
      { num: '3', title: '涂上颜色', desc: '从调色板中点击一种颜色，然后点击任何编号区域进行填充。或切换到铅笔工具进行自由绘画。随时可以撤销。' },
      { num: '4', title: '保存、打印或挑战朋友', desc: '下载你完成的杰作、打印出来，或使用挑战按钮将同一张图片分享给朋友，看谁先完成！' },
    ],
    featuresHeading: '创作和涂色所需的一切',
    featuresSub: '为儿童设计，全家喜爱。',
    features: [
      { icon: '🤖', title: 'AI 图像生成', desc: '由最先进的 FLUX AI 驱动。每张涂色页都从零开始绘制——没有两张图片完全相同。' },
      { icon: '🔢', title: '按数字涂色', desc: '每个区域都有编号并与调色板匹配。非常适合学习颜色和数字的幼儿。' },
      { icon: '⭐', title: '4 个难度级别', desc: '从简单（3-6 个区域）到极难（曼陀罗风格的复杂度）。找到适合任何年龄的完美挑战。' },
      { icon: '🖌️', title: '3 种调色板', desc: '经典蜡笔（24 种鲜艳颜色）、柔和粉彩或自然色调。还有包含 256 种颜色的 Max 模式。' },
      { icon: '✏️', title: '自由绘画', desc: '切换到铅笔工具，在涂色页上添加你自己的细节。包含完整的撤销历史记录。' },
      { icon: '🖨️', title: '打印和保存', desc: '将涂色页下载为 PNG 或直接发送到打印机。非常适合离线涂色书。' },
      { icon: '🏆', title: '多人挑战', desc: '分享链接让朋友同时涂同一张图片。计时器显示谁先完成！' },
      { icon: '🌟', title: '每日挑战', desc: '每天为所有人出现一个新词。画出每日词汇并与朋友比较结果。' },
      { icon: '🖼️', title: '个人画廊', desc: '完成的图片会自动保存到设备画廊。随时重温并继续完成它们。' },
      { icon: '🌍', title: '12 种语言', desc: '提供英语、德语、法语、西班牙语、俄语、意大利语、葡萄牙语、荷兰语、波兰语、土耳其语、中文和印地语版本。' },
      { icon: '📱', title: 'iOS 和 Android 应用', desc: '在任何浏览器中使用 Lalabuba，或下载 iOS 和 Android 原生应用获得最佳移动体验。' },
      { icon: '🆓', title: '100% 免费', desc: '无需账号，无需订阅，无广告，无应用内购买。Lalabuba 今天免费，永远免费。' },
    ],
    badgesHeading: '随处可用',
    badgesSub: '在任何浏览器中均可使用。也提供原生应用。',
    faqHeading: '常见问题',
    faqItems: [
      { q: 'Lalabuba 真的免费吗？', a: '是的，完全免费。没有广告、没有订阅、没有应用内购买，也不需要账号。Lalabuba 对所有人免费。' },
      { q: '适合哪些年龄？', a: 'Lalabuba 专为 3-12 岁儿童设计，但全家人都能享受。简单模式（6 个区域，6 种颜色）非常适合幼儿；极难模式为年龄较大的儿童和成人创造曼陀罗级别的复杂度。' },
      { q: '我可以打印涂色页吗？', a: '可以！点击打印按钮，可以打印空白线条图进行传统纸质涂色，或者打印你完成的彩色数字版本用于保存或装框。' },
      { q: '它在平板和手机上有效吗？', a: '是的。Lalabuba 完全自适应，可在任何现代浏览器中使用。为了在移动端获得最佳体验，请下载具有触控优化控件和捏合缩放功能的 iOS 或 Android 原生应用。' },
      { q: '多人挑战是如何运作的？', a: '生成涂色页后，点击"挑战朋友"获取可分享的链接。打开链接的任何人都会看到完全相同的图片。两位玩家的计时器同时运行——先完成涂色者获胜！' },
    ],
    ctaHeading: '准备好开始涂色了吗？',
    ctaSub: '无需注册。你的第一张涂色页只需一次点击。',
    ctaBtn: '打开 Lalabuba——免费 →',
    ctaOr: '或探索',
    ctaColoringPages: '热门涂色主题',
  },

  hi: {
    lang: 'hi',
    htmlLang: 'hi',
    title: 'विशेषताएं — Lalabuba कैसे काम करता है | बच्चों के लिए मुफ्त AI रंग भरने के पेज',
    description: 'Lalabuba की विशेषताएं खोजें: AI रंग पेज जेनरेशन, नंबर से रंग भरना, 4 कठिनाई स्तर, दैनिक चुनौती, मल्टीप्लेयर और बहुत कुछ। सभी के लिए मुफ्त।',
    h1: 'Lalabuba कैसे काम करता है',
    heroDesc: 'कोई भी विषय टाइप करें, AI को इसे बनाते हुए देखें, रंग भरें। बस इतना आसान है — और पूरी तरह मुफ्त।',
    heroCta: 'अभी आज़माएं — मुफ्त है →',
    stepsHeading: 'अपने परफेक्ट कलरिंग पेज के लिए 4 कदम',
    stepsSub: 'कोई अकाउंट नहीं चाहिए। कोई डाउनलोड नहीं चाहिए। किसी भी ब्राउज़र में काम करता है।',
    steps: [
      { num: '1', title: 'कोई भी विषय टाइप करें', desc: 'जो भी आप बनाना चाहते हैं वह टाइप करें — ड्रैगन, तितली, महल, यूनिकॉर्न, या अपना कोई भी रचनात्मक विचार। हमारी AI हजारों विषयों को समझती है।' },
      { num: '2', title: 'Draw! पर क्लिक करें', desc: 'हमारी AI सेकंडों में आपके विषय के लिए एक कस्टम कलरिंग पेज बनाती है — हर छवि अनूठी है और आपकी मांग के अनुसार तैयार की गई है।' },
      { num: '3', title: 'रंग भरें', desc: 'पैलेट से एक रंग टैप करें, फिर भरने के लिए किसी भी क्रमांकित क्षेत्र पर टैप करें। या मुक्तहस्त ड्राइंग के लिए पेंसिल टूल पर स्विच करें। कभी भी पूर्ववत करें।' },
      { num: '4', title: 'सेव करें, प्रिंट करें या दोस्त को चुनौती दें', desc: 'अपनी पूरी की हुई उत्कृष्ट कृति डाउनलोड करें, प्रिंट करें, या Challenge बटन का उपयोग करके दोस्त के साथ एक ही चित्र साझा करें और देखें कौन पहले खत्म करता है!' },
    ],
    featuresHeading: 'बनाने और रंग भरने के लिए जो चाहिए वो सब',
    featuresSub: 'बच्चों के लिए बनाया, पूरे परिवार को पसंद।',
    features: [
      { icon: '🤖', title: 'AI इमेज जेनरेशन', desc: 'अत्याधुनिक FLUX AI द्वारा संचालित। हर कलरिंग पेज शुरू से बनाया जाता है — कोई भी दो चित्र बिल्कुल एक जैसे नहीं होते।' },
      { icon: '🔢', title: 'नंबर से रंग भरना', desc: 'हर क्षेत्र क्रमांकित है और पैलेट से मेल खाता है। रंग और संख्याएं सीखने वाले छोटे बच्चों के लिए एकदम सही।' },
      { icon: '⭐', title: '4 कठिनाई स्तर', desc: 'आसान (3-6 क्षेत्र) से अत्यंत कठिन (मंडल-शैली की जटिलता)। किसी भी उम्र के लिए सही चुनौती खोजें।' },
      { icon: '🖌️', title: '3 रंग पैलेट', desc: 'क्लासिक क्रेयॉन (24 चटकीले रंग), सॉफ्ट पेस्टल, या नेचर टोन। साथ ही 256 रंगों के साथ Max मोड।' },
      { icon: '✏️', title: 'मुक्तहस्त ड्राइंग', desc: 'कलरिंग पेज पर अपने खुद के विवरण जोड़ने के लिए पेंसिल टूल पर स्विच करें। पूर्ण पूर्ववत इतिहास शामिल है।' },
      { icon: '🖨️', title: 'प्रिंट और सेव', desc: 'अपना कलरिंग पेज PNG के रूप में डाउनलोड करें या इसे सीधे प्रिंटर पर भेजें। ऑफलाइन कलरिंग बुक के लिए शानदार।' },
      { icon: '🏆', title: 'मल्टीप्लेयर चुनौती', desc: 'एक लिंक शेयर करें ताकि दोस्त एक ही तस्वीर को एक साथ रंग भर सके। एक टाइमर दिखाता है कौन पहले खत्म करता है!' },
      { icon: '🌟', title: 'दैनिक चुनौती', desc: 'हर दिन सभी के लिए एक नया शब्द आता है। दैनिक शब्द बनाएं और दोस्तों के साथ परिणाम की तुलना करें।' },
      { icon: '🖼️', title: 'व्यक्तिगत गैलरी', desc: 'पूरे किए गए चित्र स्वचालित रूप से आपके डिवाइस गैलरी में सहेजे जाते हैं। कभी भी वापस आएं और उन्हें जारी रखें।' },
      { icon: '🌍', title: '12 भाषाएं', desc: 'अंग्रेजी, जर्मन, फ्रेंच, स्पेनिश, रूसी, इतालवी, पुर्तगाली, डच, पोलिश, तुर्की, चीनी और हिंदी में उपलब्ध।' },
      { icon: '📱', title: 'iOS और Android ऐप्स', desc: 'किसी भी ब्राउज़र में Lalabuba उपयोग करें या सर्वोत्तम मोबाइल अनुभव के लिए iOS और Android नेटिव ऐप डाउनलोड करें।' },
      { icon: '🆓', title: '100% मुफ्त', desc: 'कोई अकाउंट नहीं, कोई सब्सक्रिप्शन नहीं, कोई विज्ञापन नहीं, कोई इन-ऐप खरीदारी नहीं। Lalabuba आज मुफ्त है और हमेशा रहेगा।' },
    ],
    badgesHeading: 'हर जगह उपलब्ध',
    badgesSub: 'किसी भी ब्राउज़र में काम करता है। नेटिव ऐप के रूप में भी उपलब्ध।',
    faqHeading: 'अक्सर पूछे जाने वाले सवाल',
    faqItems: [
      { q: 'क्या Lalabuba सच में मुफ्त है?', a: 'हां, पूरी तरह मुफ्त। कोई विज्ञापन नहीं, कोई सब्सक्रिप्शन नहीं, कोई इन-ऐप खरीदारी नहीं, और कोई अकाउंट नहीं चाहिए। Lalabuba सभी के लिए मुफ्त है।' },
      { q: 'यह किस उम्र के लिए बनाया गया है?', a: 'Lalabuba 3-12 साल के बच्चों के लिए बनाया गया है, लेकिन पूरे परिवार को पसंद आता है। Easy मोड (6 क्षेत्र, 6 रंग) छोटे बच्चों के लिए परफेक्ट है; Extreme मोड बड़े बच्चों और वयस्कों के लिए मंडल-स्तरीय जटिलता बनाता है।' },
      { q: 'क्या मैं कलरिंग पेज प्रिंट कर सकता/सकती हूं?', a: 'हां! पारंपरिक कागज पर रंग भरने के लिए खाली लाइन आर्ट प्रिंट करने के लिए Print बटन क्लिक करें, या रखने या फ्रेम करने के लिए अपनी पूरी हो गई रंगीन डिजिटल वर्शन प्रिंट करें।' },
      { q: 'क्या यह टैबलेट और फोन पर काम करता है?', a: 'हां। Lalabuba पूरी तरह रेस्पॉन्सिव है और किसी भी आधुनिक ब्राउज़र में काम करता है। मोबाइल पर सर्वोत्तम अनुभव के लिए, टच-ऑप्टिमाइज़्ड कंट्रोल और पिंच-टू-ज़ूम के साथ नेटिव iOS या Android ऐप डाउनलोड करें।' },
      { q: 'मल्टीप्लेयर चुनौती कैसे काम करती है?', a: 'कलरिंग पेज बनाने के बाद, शेयर करने योग्य लिंक पाने के लिए "दोस्त को चुनौती दें" पर क्लिक करें। जो भी लिंक खोलता है वह बिल्कुल एक ही चित्र देखता है। दोनों खिलाड़ियों के लिए टाइमर चलता है — जो पहले रंग भरना खत्म करे वो जीतता है!' },
    ],
    ctaHeading: 'रंग भरना शुरू करने के लिए तैयार हैं?',
    ctaSub: 'साइन अप करने की जरूरत नहीं। आपका पहला कलरिंग पेज एक क्लिक दूर है।',
    ctaBtn: 'Lalabuba खोलें — मुफ्त है →',
    ctaOr: 'या खोजें',
    ctaColoringPages: 'लोकप्रिय कलरिंग पेज विषय',
  },
};

module.exports = { FEATURES_LANGS };
