// STUB — generated by `flutterfire configure`. Run that command to replace
// this file with real per-platform options and wire up the native plugins.
// Until then Firebase initialisation is skipped gracefully; PostHog still works.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  // ignore: prefer_constructors_over_static_methods
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'Firebase not configured — run `flutterfire configure` to generate real options.',
    );
  }
}
